services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
    tmpfs:
      - /data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_ui
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  postgres:
    image: postgres:17.6
    container_name: postgres_server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEFAULT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  unleash:
    image: unleashorg/unleash-server:latest
    container_name: unleash_server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${UNLEASH_DB}?sslmode=disable
      UNLEASH_DEFAULT_ADMIN_USERNAME: ${UNLEASH_ADMIN_USERNAME}
      UNLEASH_DEFAULT_ADMIN_PASSWORD: ${UNLEASH_ADMIN_PASSWORD}

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

volumes:
  postgres_data:
  pgadmin_data:
  redisinsight_data: